import json

import pytest
from unittest.mock import MagicMock, patch

from services import emailService, receiptService


@pytest.mark.asyncio
async def test_send_otp_email_uses_neutral_routex_copy(monkeypatch):
    calls = []

    def fake_post(url, headers=None, data=None, timeout=None):
        calls.append(
            {
                "url": url,
                "headers": headers,
                "data": data,
                "timeout": timeout,
            }
        )
        response = MagicMock()
        response.status_code = 200
        response.text = "ok"
        return response

    monkeypatch.setattr(emailService.settings, "RESEND_API_KEY", "resend_test_key")
    monkeypatch.setattr(emailService.settings, "AUTH_EMAIL", "auth@routex.xoroai.cloud")
    monkeypatch.setattr(emailService.requests, "post", fake_post)

    await emailService.send_otp_email("buyer@example.com", "535627")

    assert len(calls) == 1
    payload = calls[0]["data"]
    assert calls[0]["url"] == emailService.RESEND_API_URL
    assert calls[0]["headers"]["Authorization"] == "Bearer resend_test_key"
    assert calls[0]["headers"]["Content-Type"] == "application/json"
    assert calls[0]["timeout"] == 15
    payload_json = json.loads(payload)
    assert '"subject": "Your RouteX verification code"' in payload
    assert "RouteX" in payload
    assert "X-Aggregator" not in payload
    assert "535627" in payload
    html_text = " ".join(payload_json["html"].split())
    assert "signing in or creating a RouteX account" in html_text


def test_otp_template_is_brand_clean():
    html = emailService._load_template(emailService.OTP_TEMPLATE_PATH).replace(
        "{{OTP_CODE}}", "535627"
    )

    assert "RouteX" in html
    assert "X-Aggregator" not in html
    assert "{{" not in html
    assert "535627" in html


def test_receipt_templates_use_routex_branding():
    transaction = MagicMock()
    transaction.reference = "TXN_001"
    transaction.type = "credit"
    transaction.mode = "test"
    transaction.customer.email = "buyer@example.com"
    transaction.details = {
        "customer_name": "Ada Obi",
        "account_number": "1234567890",
        "bank": "Test Bank",
    }
    transaction.currency = "NGN"
    transaction.amount = 2500
    transaction.narration = "Payment received"
    transaction.created_at.strftime.return_value = "26 Mar 2026, 01:00 PM"
    transaction.merchant_id = "agg-7258c"
    transaction.merchant.name = "RouteX Merchant"
    transaction.status = "success"

    customer_html = receiptService.generate_customer_receipt_html(transaction)
    merchant_html = receiptService.generate_receipt_html(transaction)
    customer_text = receiptService.generate_customer_receipt_text(transaction)

    assert "X-Aggregator" not in customer_html
    assert "X-Aggregator" not in merchant_html
    assert "X-Aggregator" not in customer_text
    assert "RouteX" in customer_html
    assert "RouteX" in merchant_html
    assert "<img" not in customer_html
    assert "<img" not in merchant_html
    assert "res.cloudinary.com" not in customer_html
    assert "res.cloudinary.com" not in merchant_html
    assert "Transaction Receipt" in merchant_html
    assert "Customer Transaction Receipt" in customer_html
    assert "Generated by RouteX" in customer_text
