"""initial

Revision ID: 1b54993c47bd
Revises: 
Create Date: 2026-02-23 14:47:16.606406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b54993c47bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('percentage_charge', sa.Float(), nullable=True),
    sa.Column('flat_charge', sa.Float(), nullable=True),
    sa.Column('payout_percentage_charge', sa.Float(), nullable=False),
    sa.Column('payout_flat_charge', sa.Float(), nullable=False),
    sa.Column('test_balance', sa.Float(), nullable=True),
    sa.Column('live_balance', sa.Float(), nullable=True),
    sa.Column('live_webhook_url', sa.Text(), nullable=True),
    sa.Column('test_webhook_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_merchant_id'), 'merchant', ['id'], unique=False)
    op.create_table('processor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('charge', sa.Float(), nullable=True),
    sa.Column('markup', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bulk_payout',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('merchant_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESSFUL', 'FAILED', 'PARTIAL', name='bulkpayoutstatus'), nullable=True),
    sa.Column('transaction_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('customer_merchant',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'merchant_id')
    )
    op.create_table('merchant_processor',
    sa.Column('merchant_id', sa.String(length=50), nullable=False),
    sa.Column('processor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.ForeignKeyConstraint(['processor_id'], ['processor.id'], ),
    sa.PrimaryKeyConstraint('merchant_id', 'processor_id')
    )
    op.create_table('payment_links',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount_type', sa.Enum('STATIC', 'DYNAMIC', name='amounttype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redirect_url', sa.String(length=500), nullable=True),
    sa.Column('_metadata', sa.Text(), nullable=True),
    sa.Column('merchant_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_links_reference'), 'payment_links', ['reference'], unique=True)
    op.create_table('payout_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('merchant_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_categories_id'), 'payout_categories', ['id'], unique=False)
    op.create_table('token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.String(length=50), nullable=True),
    sa.Column('secret_key', sa.Text(), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_merchants',
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('merchant_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'merchant_id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('percentage_charge', sa.Float(), nullable=False),
    sa.Column('flat_charge', sa.Float(), nullable=False),
    sa.Column('payout_percentage_charge', sa.Float(), nullable=False),
    sa.Column('payout_flat_charge', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'currency', 'mode', name='uq_merchant_currency_mode')
    )
    op.create_table('bulk_payout_category',
    sa.Column('bulk_payout_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bulk_payout_id'], ['bulk_payout.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['payout_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bulk_payout_id', 'category_id')
    )
    op.create_table('payout_beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bank_code', sa.String(length=10), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('default_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('narration', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('merchant_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['payout_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_beneficiaries_id'), 'payout_beneficiaries', ['id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('CREDIT', 'DEBIT', name='transactiontype'), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('processor', sa.Enum('FLUTTERWAVE', 'KORA', 'PAYSTACK', name='transactionprocessor'), nullable=False),
    sa.Column('merchant_id', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('processor_reference', sa.String(length=100), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('charge', sa.Float(), nullable=True),
    sa.Column('processor_charge', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'ABANDONED', name='transactionstatus', native_enum=False), nullable=True),
    sa.Column('redirect_url', sa.Text(), nullable=True),
    sa.Column('notification_url', sa.Text(), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bulk_payout_id', sa.Integer(), nullable=True),
    sa.Column('payment_link_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bulk_payout_id'], ['bulk_payout.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.ForeignKeyConstraint(['payment_link_id'], ['payment_links.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processor_reference')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_index(op.f('ix_payout_beneficiaries_id'), table_name='payout_beneficiaries')
    op.drop_table('payout_beneficiaries')
    op.drop_table('bulk_payout_category')
    op.drop_table('wallets')
    op.drop_table('user_merchants')
    op.drop_table('token')
    op.drop_index(op.f('ix_payout_categories_id'), table_name='payout_categories')
    op.drop_table('payout_categories')
    op.drop_index(op.f('ix_payment_links_reference'), table_name='payment_links')
    op.drop_table('payment_links')
    op.drop_table('merchant_processor')
    op.drop_table('customer_merchant')
    op.drop_table('bulk_payout')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('processor')
    op.drop_index(op.f('ix_merchant_id'), table_name='merchant')
    op.drop_table('merchant')
    op.drop_table('customers')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
