from fpdf import FPDF
from datetime import datetime
from database.models.Transaction import Transaction
from enums.transactionEnums import TransactionType
import tempfile
import imgkit
# Path to the logo file
logo_path = "logo.png"
logo_url = r"https://res.cloudinary.com/dwcx4ksau/image/upload/v1757103183/logo_niidpc.png"

class ReceiptPDF(FPDF):
    def header(self):
        
        self.image(logo_path, x=85, w=40)
        self.ln(30)
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, "Transaction Receipt", ln=True, align="C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128)
        self.cell(0, 10, "Generated by X-Aggregator", 0, 0, "C")

    def add_transaction_details(self, transaction: Transaction):
        self.set_font("Helvetica", "", 12)
        self.set_text_color(0)

        def line(label, value):
            self.set_font("Helvetica", "B", 12)
            self.cell(60, 10, f"{label}:", ln=0)
            self.set_font("Helvetica", "", 12)
            self.cell(0, 10, f"{value}", ln=1)

        line("Transaction Reference", transaction.reference)
        line("Transaction type", f"{transaction.type}")
        line("Mode", f"{transaction.mode}")
        line("Customer email", transaction.customer.email)
        line("Customer Name", transaction.details.get("customer_name", "N/A")if transaction.details else "N/A")
        line("Account Number", transaction.details.get("account_number", "N/A") if transaction.details else "N/A")
        line("Bank", transaction.details.get("bank", "N/A")if transaction.details else "N/A")
        line("Amount", f'{transaction.currency} {transaction.amount:,.2f}')
        line("Narration", transaction.narration or  "N/A")
        line("Date", transaction.created_at.strftime("%d %b %Y, %I:%M %p"))

    def add_customer_transaction_details(self, transaction: Transaction):
        self.set_font("Helvetica", "", 12)
        self.set_text_color(0)

        def line(label, value):
            self.set_font("Helvetica", "B", 12)
            self.cell(60, 10, f"{label}:", ln=0)
            self.set_font("Helvetica", "", 12)
            self.cell(0, 10, f"{value}", ln=1)

        customer_transaction_type = TransactionType.DEBIT if transaction.type == TransactionType.CREDIT else TransactionType.CREDIT
        line("Transaction Reference", transaction.reference)
        line("Mode", f"{transaction.mode}")
        line("Transaction type", f"{customer_transaction_type}")
        line("Transaction status", f"{Transaction.status}")
        line("Mode", f"{transaction.mode}")
        line('Merchant ID', transaction.merchant_id)
        line("Customer email", transaction.customer.email)
        line("Account Number", transaction.details.get("account_number", "N/A") if transaction.details else "N/A")
        line("Bank", transaction.details.get("bank", "N/A")if transaction.details else "N/A")
        line("Amount", f'{transaction.currency} {transaction.amount:,.2f}')
        line("Narration", transaction.narration if transaction.narration else f"Payment from/to {transaction.merchant.name}")
        line("Date", transaction.created_at.strftime("%d %b %Y, %I:%M %p"))

class ReceiptHTML:
    def __init__(self):
        self.logo_path = logo_url

    def header(self, title: str) -> str:
        return f"""
        <div style="text-align:center; margin-bottom:20px;">
            <img src="{self.logo_path}" alt="Logo" style="max-width:120px; margin-bottom:10px;">
            <h2 style="font-family:Helvetica, Arial, sans-serif; margin:0;">{title}</h2>
        </div>
        """

    def footer(self) -> str:
        return """
        <div style="text-align:center; margin-top:30px; font-size:12px; color:#888; font-family:Helvetica, Arial, sans-serif;">
            Generated by X-Aggregator
        </div>
        """

    def line(self, label: str, value: str) -> str:
        return f"""
        <tr>
            <td style="padding:8px; font-weight:bold; font-family:Helvetica, Arial, sans-serif; border-bottom:1px solid #eee; width:40%;">{label}:</td>
            <td style="padding:8px; font-family:Helvetica, Arial, sans-serif; border-bottom:1px solid #eee;">{value}</td>
        </tr>
        """

    def add_transaction_details(self, transaction: Transaction) -> str:
        return f"""
        <table style="width:100%; border-collapse:collapse; margin-top:20px;">
            {self.line("Transaction Reference", transaction.reference)}
            {self.line("Mode", f"{transaction.mode}")}
            {self.line("Transaction type", f"{transaction.type}")}
            {self.line("Customer email", transaction.customer.email)}
            {self.line("Customer Name", transaction.details.get("customer_name", "N/A")if transaction.details else "N/A")}
            {self.line("Account Number", transaction.details.get("account_number", "N/A")if transaction.details else "N/A")}
            {self.line("Bank", transaction.details.get("bank", "N/A")if transaction.details else "N/A")}
            {self.line("Amount", f'{transaction.currency} {transaction.amount:,.2f}')}
            {self.line("Narration", transaction.narration or "N/A")}
            {self.line("Date", transaction.created_at.strftime("%d %b %Y, %I:%M %p"))}
        </table>
        """

    def add_customer_transaction_details(self, transaction: Transaction) -> str:
        customer_transaction_type = TransactionType.DEBIT if transaction.type == TransactionType.CREDIT else TransactionType.CREDIT

        return f"""
        <table style="width:100%; border-collapse:collapse; margin-top:20px;">
            {self.line("Transaction Reference", transaction.reference)}
            {self.line("Mode", f"{transaction.mode}")}
            {self.line("Transaction type", f"{customer_transaction_type}")}
            {self.line("Transaction status", f"{transaction.status}")}
            {self.line("Merchant ID", transaction.merchant_id)}
            {self.line("Customer email", transaction.customer.email)}
            {self.line("Account Number", transaction.details.get("account_number", "N/A")if transaction.details else "N/A")}
            {self.line("Bank", transaction.details.get("bank", "N/A")if transaction.details else "N/A")}
            {self.line("Amount", f'{transaction.currency} {transaction.amount:,.2f}')}
            {self.line("Narration", transaction.narration if transaction.narration else f"Payment from/to {transaction.merchant.name}")}
            {self.line("Date", transaction.created_at.strftime("%d %b %Y, %I:%M %p"))}
        </table>
        """

class ReceiptImage:
    def __init__(self):
        self.logo_path = logo_url

    def header(self, title: str) -> str:
        return f"""
        <div style="text-align:center; margin-bottom:20px;">
            <img src="{self.logo_path}" alt="Logo" style="max-width:120px; margin-bottom:10px;">
            <h2 style="font-family:Helvetica, Arial, sans-serif; margin:0;">{title}</h2>
        </div>
        """

    def footer(self) -> str:
        return """
        <div style="text-align:center; margin-top:30px; font-size:12px; color:#888; font-family:Helvetica, Arial, sans-serif;">
            Generated by X-Aggregator
        </div>
        """

    def line(self, label: str, value: str) -> str:
        return f"""
        <tr>
            <td style="padding:8px; font-weight:bold; font-family:Helvetica, Arial, sans-serif; border-bottom:1px solid #eee; width:40%;">{label}:</td>
            <td style="padding:8px; font-family:Helvetica, Arial, sans-serif; border-bottom:1px solid #eee;">{value}</td>
        </tr>
        """

    def add_transaction_details(self, transaction: Transaction) -> str:
        return f"""
        <table style="width:100%; border-collapse:collapse; margin-top:20px;">
            {self.line("Transaction Reference", transaction.reference)}
            {self.line("Transaction type", f"{transaction.type}")}
            {self.line("Mode", f"{transaction.mode}")}
            {self.line("Customer email", transaction.customer.email)}            
            {self.line("Customer Name", transaction.details.get("customer_name", "N/A") if transaction.details else "N/A")}
            {self.line("Account Number", transaction.details.get("account_number", "N/A") if transaction.details else "N/A")}
            {self.line("Bank", transaction.details.get("bank", "N/A")if transaction.details else "N/A")}
            {self.line("Amount", f'{transaction.currency} {transaction.amount:,.2f}')}
            {self.line("Narration", transaction.narration or "N/A")}
            {self.line("Date", transaction.created_at.strftime("%d %b %Y, %I:%M %p"))}
        </table>
        """

    def add_customer_transaction_details(self, transaction: Transaction) -> str:
        customer_transaction_type = TransactionType.DEBIT if transaction.type == TransactionType.CREDIT else TransactionType.CREDIT

        return f"""
        <table style="width:100%; border-collapse:collapse; margin-top:20px;">
            {self.line("Transaction Reference", transaction.reference)}
            {self.line("Mode", f"{transaction.mode}")}
            {self.line("Transaction type", f"{customer_transaction_type}")}
            {self.line("Transaction status", f"{transaction.status}")}
            {self.line("Merchant ID", transaction.merchant_id)}
            {self.line("Customer email", transaction.customer.email)}
            {self.line("Account Number", transaction.details.get("account_number", "N/A") if transaction.details else "N/A")}
            {self.line("Bank", transaction.details.get("bank", "N/A")if transaction.details else "N/A")}
            {self.line("Amount", f'{transaction.currency} {transaction.amount:,.2f}')}
            {self.line("Narration", transaction.narration if transaction.narration else f"Payment from/to {transaction.merchant.name}")}
            {self.line("Date", transaction.created_at.strftime("%d %b %Y, %I:%M %p"))}
        </table>
        """

def generate_receipt_pdf(transaction: Transaction)->str:
    """Returns output path to the generated receipt"""
    # if transaction.type != TransactionType.DEBIT:
    #     raise ValueError("Receipts can only be generated for debit transactions.")

    temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    output_path = temp_file.name
    temp_file.close()

    pdf = ReceiptPDF()
    pdf.add_page()
    pdf.add_transaction_details(transaction)
    pdf.output(output_path)
    return output_path

def generate_receipt_pdf_bytes(transaction: Transaction) -> bytes:
    """Returns PDF as bytes (used for email attachments)."""
    pdf = ReceiptPDF()
    pdf.add_page()
    pdf.add_transaction_details(transaction)
    return bytes(pdf.output())

def getenerate_customer_receipt_pdf(transaction: Transaction)->str:
    """Returns output path to the generated receipt"""
    # if transaction.type != TransactionType.CREDIT:
    #     raise ValueError("Receipts can only be generated for credit transactions.")

    temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    output_path = temp_file.name
    temp_file.close()

    pdf = ReceiptPDF()
    pdf.add_page()
    pdf.add_customer_transaction_details(transaction)
    pdf.output(output_path)
    return output_path

def getenerate_customer_receipt_pdf_bytes(transaction: Transaction) -> bytes:
    """Returns customer PDF as bytes (used for email attachments)."""
    pdf = ReceiptPDF()
    pdf.add_page()
    pdf.add_customer_transaction_details(transaction)
    return bytes(pdf.output())

def generate_receipt_html(transaction: Transaction) -> str:
    """Returns generated receipt HTML string"""
    # if transaction.type != TransactionType.DEBIT:
    #     raise ValueError("Receipts can only be generated for debit transactions.")

    receipt = ReceiptHTML()
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"><title>Transaction Receipt</title></head>
    <body style="background:#f9f9f9; padding:30px;">
        <div style="max-width:600px; margin:auto; background:#fff; padding:20px; border-radius:8px; box-shadow:0 0 8px rgba(0,0,0,0.1);">
            {receipt.header("Transaction Receipt")}
            {receipt.add_transaction_details(transaction)}
            {receipt.footer()}
        </div>
    </body>
    </html>
    """

    return html_content

def generate_customer_receipt_html(transaction: Transaction) -> str:
    """Returns output path to the generated customer receipt HTML"""
    # if transaction.type != TransactionType.CREDIT:
    #     raise ValueError("Customer receipts can only be generated for credit transactions.")

    receipt = ReceiptHTML()
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"><title>Customer Transaction Receipt</title></head>
    <body style="background:#f9f9f9; padding:30px;">
        <div style="max-width:600px; margin:auto; background:#fff; padding:20px; border-radius:8px; box-shadow:0 0 8px rgba(0,0,0,0.1);">
            {receipt.header("Customer Transaction Receipt")}
            {receipt.add_customer_transaction_details(transaction)}
            {receipt.footer()}
        </div>
    </body>
    </html>
    """

    return html_content

def generate_receipt_image(transaction: Transaction) -> str:
    """Generate transaction receipt as PNG"""
    # if transaction.type != TransactionType.DEBIT:
    #     raise ValueError("Receipts can only be generated for debit transactions.")

    receipt = ReceiptImage()
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"><title>Transaction Receipt</title></head>
    <body style="background:#f9f9f9; padding:30px;">
        <div style="max-width:600px; margin:auto; background:#fff; padding:20px; border-radius:8px; box-shadow:0 0 8px rgba(0,0,0,0.1);">
            {receipt.header("Transaction Receipt")}
            {receipt.add_transaction_details(transaction)}
            {receipt.footer()}
        </div>
    </body>
    </html>
    """

    temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".png")
    output_path = temp_file.name
    temp_file.close()

    imgkit.from_string(html_content, output_path)
    return output_path

def generate_customer_receipt_image(transaction: Transaction) -> str:
    """Generate customer receipt as PNG"""
    # if transaction.type != TransactionType.CREDIT:
    #     raise ValueError("Customer receipts can only be generated for credit transactions.")

    receipt = ReceiptImage()
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"><title>Customer Transaction Receipt</title></head>
    <body style="background:#f9f9f9; padding:30px;">
        <div style="max-width:600px; margin:auto; background:#fff; padding:20px; border-radius:8px; box-shadow:0 0 8px rgba(0,0,0,0.1);">
            {receipt.header("Customer Transaction Receipt")}
            {receipt.add_customer_transaction_details(transaction)}
            {receipt.footer()}
        </div>
    </body>
    </html>
    """

    temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".png")
    output_path = temp_file.name
    temp_file.close()

    imgkit.from_string(html_content, output_path)
    return output_path

def generate_customer_receipt_text(transaction: Transaction) -> str:
    """Return a plain text receipt for customers as a string."""
    # if transaction.type != TransactionType.CREDIT:
    #     raise ValueError("Text receipts are only generated for credit transactions.")
    transaction_type = TransactionType.DEBIT if transaction.type == TransactionType.CREDIT else TransactionType.CREDIT
    receipt_lines = []
    receipt_lines.append("== Transaction Receipt ==")
    receipt_lines.append(f"Transaction Reference: {transaction.reference}")
    receipt_lines.append(f"Transaction Type: {transaction_type}")
    receipt_lines.append(f"Transaction Status: {transaction.status}")
    receipt_lines.append(f"Mode: {transaction.mode}")
    receipt_lines.append(f"Merchant ID: {transaction.merchant_id}")
    receipt_lines.append(f"Customer Email: {transaction.customer.email}")
    receipt_lines.append("Account Number", transaction.details.get("account_number", "N/A") if transaction.details else "N/A")
    receipt_lines.append("Bank", transaction.details.get("bank", "N/A")if transaction.details else "N/A")
    receipt_lines.append(f"Amount: {transaction.currency} {transaction.amount:,.2f}")
    receipt_lines.append(transaction.narration if transaction.narration else f"Narration: Payment to {transaction.merchant.name}" if transaction.type == TransactionType.CREDIT else f"Narration: Payment from {transaction.merchant.name}")

    receipt_lines.append(
        f"Date: {transaction.created_at.strftime('%d %b %Y, %I:%M %p')}"
    )
    receipt_lines.append("============================")
    receipt_lines.append("Generated by X-Aggregator")

    return "\n".join(receipt_lines)